version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: lifaalbina/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/app/media/
  frontend:
    env_file: .env
    image: lifaalbina/kittygram_frontend
    volumes:
      - static:/static
  gateway:
    image: lifaalbina/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/media